### PR TITLE
61 visualise point features

### LINKED ISSUE #61: visualise point features from source dataset in map
#72 is required for this

### PR DESCRIPTION
**Pull request by kardwen**
I used switches instead of checkboxes, see if you like it.
I also changed the start configuration so that the features are shown, and simplified it a little bit.
The width of the at least/ less than button is now fixed.

### CODE REVIEW

**Comment by kardwen** [comment]
There seems to be an issue with pre-configurations that needs to be resolved first

**Comment by jbalzer12** [comment]
Could you change the museum icon? I think it's not clear what is meant.
Maybe something like [this](https://de.cleanpng.com/png-geuyor/)

**Comment by kardwen** [comment]
That is an icon for theaters that you posted.

**Comment by jbalzer12** [comment]
> That is an icon for theaters that you posted.

You're right. changed the comment

**Comment by kardwen** [comment]
I also like the new icons, You can just replace the old icons with them, the theater icon is propably the most important one. I think that icons should have a transparent background and be colored black.

**Comment by kardwen** [comment]
grafik

wtf @ https://github.com/vuetifyjs/vuetify/issues/1443

**Comment by kardwen** [comment]
I think we should also adjust the tooltip text of the slider because it is negated.

**Comment by kardwen** [comment]
"Move the slider to remove all areas that have a certain distance to museums." => "Move the slider to include areas inside or outside a certain radius of museums" for example

**Comment by kardwen** [comment]
Would it be difficult to add the icons to the legend?

**Comment by jbalzer12** [comment]
> Would it be difficult, to add the icons to the legend?

You can do that if you got the time. I sincerely don’t have the time before the deadline on Sunday

**Review by jbalzer12 — APPROVED** [review]

**Pull request merged**
