### PR TITLE
Update

### PR DESCRIPTION
**Pull request by xcomagent95**
Features can now be retrieved via the API. It functions like thie:

HOST:PORT/features/theaters or HOST:PORT/features/museums

Or check the API document :D

#72

### CODE REVIEW

**Comment by kardwen** [comment]
I think there is still an issue with CORS but I'm not sure about it

**Comment by kardwen** [comment]
I have a branch that shows querying of the features, I will link it

**Comment by jbalzer12** [comment]
> I have a branch that shows querying of the features, I will link it

#61 is already an issue for the task. And there already exists a branch, too :)

**Comment by kardwen** [comment]
https://github.com/phuef/Geoinformation-in-Society-22/compare/main...102-fetch-features
Here is my example. sorry I overlooked the existing issue, but maybe my example is still helpfull for resolving the issue

**Pull request merged**
