### PR TITLE
Smooth result polygons

### PR DESCRIPTION
**Pull request by kardwen**
# Testing smoothing of polygons with turf.js

I simplify the polygons before smoothing for better results, let me know if you have a different idea! I experimented a little bit with different parameters as well.

### CODE REVIEW

**Comment by kardwen** [comment]
I will move the refactoring of the result variable to a different commit, so that the smoothing can be reverted easily with `git revert` and then merge it.

**Comment by jbalzer12** [comment]
What do you mean with cherry picking?

**Comment by jbalzer12** [comment]
Didn't this branch include the exact same changes than your direct push to main?

**Comment by kardwen** [comment]
yes

https://git-scm.com/docs/git-cherry-pick

**Pull request closed without merging**
