### PR TITLE
Backend with more Data

### PR DESCRIPTION
**Pull request by xcomagent95**
Hi all,

i added the datsets and hopefully fixed the logical error (inverse interpretation etc.). New version should be on dockerhub as version 0.1
#106 
#107

### CODE REVIEW

**Comment by phuef** [comment]
Looks good :)
Just one thing: Please add the version to the docker-compose. (v0.1 instead of latest) Otherwise, the new image won't be pulled automatically, because under the latest tag is still an image with an old state. Or just update the image under the latest tag

**Comment by phuef** [comment]
hab den commit gerade erst gesehen. Dann kannst du den Kommentar ignorieren

**Comment by kardwen** [comment]
Did you update it on docker hub as well? :)

**Comment by jbalzer12** [comment]
I again first deleted the old container and downloaded the new one from scratch. But did anyone test, if the latest version gets pulled automatically only by running docker-compose up?

**Comment by kardwen** [comment]
Yes, it does. Results look good as well!

**Comment by xcomagent95** [comment]
> I again first deleted the old container and downloaded the new one from scratch. But did anyone test, if the latest version gets pulled automatically only by running docker-compose up? 
> 

The docker-compose does now pull the version 0.1 which i just pushed :D

**Pull request merged**
